name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Optionally set up Node.js if needed
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          yarn install
          echo "Dependencies installed successfully."

      - name: Run build
        run: |
          echo "Running build..."
          yarn run build
          echo "Build completed."

      # Deploy to EC2 using SSH
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "${EC2_SSH_KEY}" | tr -d '\r' > ssh_key
          chmod 600 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key $EC2_USER@$EC2_HOST << 'EOF'
            cd /path/to/your/project
            git pull origin main
            yarn install
            yarn run build
            pm2 stop all || true
            pm2 start yarn --name "your-app-name" -- start
            pm2 save
          EOF
