name: Deploy Strapi
on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Install PM2
        run: npm install pm2 -D  # Install PM2 as a dev dependency
      - name: Build Strapi
        run: npm run build  # Replace with your build command (if needed)
      - name: Start Strapi with PM2
        run: pm2 start npm -- name "Strapi" -- start
      - name: Stop Strapi with PM2 (optional)  # This step will stop Strapi after starting it
        run: pm2 stop Strapi
