name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn run build

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY_ID: ${{ secrets.EC2_SSH }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
            git clone https://github.com/Adam1911818/strapi-serverless.git
            yarn install
            yarn run build
            pm2 stop all || true
            pm2 start yarn --name "mystrapi" -- start
            pm2 save

