name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add setup-node if needed
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          yarn install
          echo "Dependencies installed successfully."

      - name: Run build
        run: |
          echo "Running build..."
          yarn run build
          echo "Build completed."

      - name: SSH Deploy
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          ssh-known-hosts: ${{ secrets.EC2_SSH }}
          remote-port: 22
          remote-user: ${{ secrets.EC2_USER }}
          ssh-authentication-timeout: 120s
          ssh-run: |
            cd /path/to/your/project
            git pull origin main
            yarn install
            yarn run build
            pm2 stop all || true
            pm2 start yarn --name "your-app-name" -- start
            pm2 save
