name: Deploy Strapi

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build Strapi
        run: npm run build  # Replace with your build command
      - name: Start Strapi
        run: npm run start  # Replace with your start command
  deploy_infrastructure:  # New job for Terraform deployment
    runs-on: ubuntu-latest  # Consider using a runner with Terraform installed
    steps:
      - uses: actions/checkout@v3  # Checkout the entire repository
      - name: Apply Terraform configuration (Optional - Manual approval)
        uses: hashicorp/terraform@v2
        with:
          args: plan -out=tfplan
      - name: Apply Terraform changes (Optional - Manual approval)
          run: terraform apply tfplan  # Replace with appropriate Terraform command
